### ISSUE TITLE
git commands' aren't working?

### ISSUE THREAD

**Issue by kevincantu** [calebmeyer/git-links#1]
On my Windows machine, at least, I see that the Alt+Ctrl+O copy command is partly working.  I end up getting output like the following, though:
```
/blob/C:/full/path/to/file.json#L3
```

If I modify [this line](https://github.com/calebmeyer/git-links/blob/master/lib/git-links.coffee#L52) to return the string "BANANA" instead of the variable stdout, I get this:
```
BANANA/blob/BANANAC:/Users/kevin/SLL/Validation/manifest.json#L19
```

So it's close, but not quite doing what it should be!  :sweat_smile: 

Git is currently on my path like so:
```
C:\Users\kevin\SLL\Validation>where git
C:\Program Files\Git\cmd\git.exe
```

Not sure what the deal is.

That said, I like where you're going with this little plugin!  Very useful, @calebmeyer!!

**Comment by calebmeyer** [comment]
Hey, thanks for the kind words. This is my first atom plugin. 

Is your git repo initialized? More specifically, is there output to `git config --get remote.origin.url` when you run it on the command line?

The command runs three git commands, and it looks like we're not successfully capturing the output of any of them. [One gets the origin url](https://github.com/calebmeyer/git-links/blob/1d85694504936bf5bc8122cb19867444e386083e/lib/git-links.coffee#L24), [one gets the commit hash](https://github.com/calebmeyer/git-links/blob/1d85694504936bf5bc8122cb19867444e386083e/lib/git-links.coffee#L27), and [one gets the absolute path to the root of your git directory](https://github.com/calebmeyer/git-links/blob/1d85694504936bf5bc8122cb19867444e386083e/lib/git-links.coffee#L30). I use the absolute path to the root directory along with the absolute path to the file to get the relative path to the file ( `manifest.json` in your case).

**Comment by calebmeyer** [comment]
Just a note, I'm also using windows, and also have git in that exact same location.

**Comment by calebmeyer** [comment]
Okay, I was able to successfully reproduce this. The problem is that the git command is currently getting run wherever atom was started. If you use `atom .` and stay in that one project, everything works fine. If you remove the project/click the icon in your taskbar, I'm not actually sure where the git command is getting run. I'm going to do some testing so I can figure out how to have the proper working directory for git commands.

**Comment by calebmeyer** [comment]
Example after adding in better error logging:
![2017-06-09 21_28_50-developer tools - file____c__users_cm022291_appdata_local_atom_app-1 18 0-beta3_](https://user-images.githubusercontent.com/3342777/26999251-b14d1c22-4d5a-11e7-991f-e92f4817a2bd.png)

**Comment by calebmeyer** [comment]
Good news. BufferedProcess passes along any options you send to Node's ChildProcess.spawn method, so I was able to set a current working directory for the git command.

I have no idea if it will work with submodules, but it should fix the issue you were seeing, @kevincantu.

Please note that I removed the default keybind and changed the command names slightly.

**Comment by kevincantu** [comment]
:beer:
